icons_format = " {icon} "

[theme]
theme = "ctp-mocha"

[icons]
icons = "awesome4"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "sound"

[[block]]
block = "vpn"
driver = "mullvad"
format_connected = " $icon "
format_disconnected = " $icon "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
